version: '3.9'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: contacts
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: no
    command: --init-file /data/application/init.sql
    volumes:
      - ./docker/mysql/init.sql:/data/application/init.sql
    ports:
      - '9906:3306'

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - '9000:80'
    volumes:
      - ./:/var/www/html/

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - ./:/var/www/html/

